config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/lookup'
  post "/home/lookup" => 'home/lookup'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :usuario_correcto, only: %i[ show edit update destroy ]

  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all

    require 'net/http'
    require 'json'

    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=100&CMC_PRO_API_KEY=c93b03ea-b0d3-4f24-8908-2c2ac8494af0'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @array1 = JSON.parse(@response).to_a
    @array2 =@array1[1].to_a
    
    @lookup_crypto = @array2[1].to_a
    @ganapierde = 0
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
    require 'net/http'
    require 'json'

    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=100&CMC_PRO_API_KEY=c93b03ea-b0d3-4f24-8908-2c2ac8494af0'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @array1 = JSON.parse(@response).to_a
    @array2 =@array1[1].to_a
    
    @show_crypto = @array2[1].to_a
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:simbolo, :user_id, :cost_per, :amount_owned)
    end

    def usuario_correcto
      @correcto = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "No está autorizado" if @correcto.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=100&CMC_PRO_API_KEY=c93b03ea-b0d3-4f24-8908-2c2ac8494af0'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @array1 = JSON.parse(@response).to_a
    @array2 =@array1[1].to_a
    
    @coins = @array2[1].to_a
    
  end
  def nosotros
  end
  def lookup
    require 'net/http'
    require 'json'

    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=100&CMC_PRO_API_KEY=c93b03ea-b0d3-4f24-8908-2c2ac8494af0'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @array1 = JSON.parse(@response).to_a
    @array2 =@array1[1].to_a
    
    @lookup_coin = @array2[1].to_a
    
  
    @simbolo = params[:sym]

    if @simbolo
      @simbolo = @simbolo.upcase
    end
    if @simbolo == ""
      @simbolo = "Has olvidado escribir la búsqueda"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :simbolo %>
    <%= form.text_field :simbolo %>
  </div>

  <div class="field">
    
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Criptomonedas</h1>
<div class="table-responsive">
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Precio Actual</th>
      <th scope="col">Invertido</th>
      <th scope="col">Se Cobraría</th>
      <th scope="col">Ganancia/Perdida</th>
      <th scope="col">Precio inicial</th>
      <th scope="col">Cantidad</th>
      
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <% if crypto.simbolo %>
          <% crypto.simbolo = crypto.simbolo.upcase %>
        <% end %>
        <tr scope="row">
        <% for x in @lookup_crypto %>
          <% if crypto.simbolo == x["symbol"] %>
            <td><%= link_to x["name"], crypto %> </td>
            <td>$<%= number_with_precision(x["quote"]["USD"]["price"], :precision=>2) %> </td>
            <td>$<%= crypto.cost_per * crypto.amount_owned %> </td>
            <td>$<%= number_with_precision((x["quote"]["USD"]["price"].to_d * crypto.amount_owned), :precision=>2) %> </td>
            <td>$<%= number_with_precision(((x["quote"]["USD"]["price"].to_d * crypto.amount_owned) - (crypto.amount_owned  * crypto.cost_per)), :precision=>2)  %>  </td>
            <% @ganapierde +=  (x["quote"]["USD"]["price"].to_d * crypto.amount_owned) - (crypto.amount_owned  * crypto.cost_per)  %>
          <% end %>
        <% end %>

          <td><%= crypto.cost_per %></td>
          <td><%= crypto.amount_owned %></td>
          
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
</div>
<br/>
<br/>
<strong>Portfolio Ganancias/Perdidas: </strong> <%= number_to_currency(@ganapierde) %> 
<br/>
<br/>

<%= link_to 'Nueva Cripto', new_crypto_path, class:"btn btn-outline-success" %>

app/views/cryptos/new.html.erb
<h1>Nueva Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<% for x in @show_crypto %>
    <% if @crypto.simbolo == x["symbol"] %>
        <% crypto_name = x["name"] %> 
        <% crypto_price = number_to_currency(x["quote"]["USD"]["price"]) %> 
        
           
    <% end %>
<% end %>





<div class="card">
  <div class="card-header">
    <strong><%= @crypto.simbolo %></strong>
  
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong><%= crypto_name %> </strong> </h5>
    <p class="card-text">Precio actual: <%= crypto_price %></p>
    <p class="card-text">Pagado a: <%= @crypto.cost_per %></p>
    <p class="card-text">Cantidad: <%= @crypto.amount_owned %></p>

    <%= link_to 'Editar', edit_crypto_path(@crypto),class:"btn btn-outline-primary" %> 
    <%= link_to 'Borrar', crypto_path(@crypto), method: :delete, data: { confirm: 'Estás seguro?' },class:"btn btn-outline-primary" %>
    <%= link_to 'Atras', cryptos_path, class:"btn btn-outline-primary" %> 
  </div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name,msg| %>
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
	 <%= content_tag(:div, msg) %>
	  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
 <% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Crypto", root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "Buscar", home_lookup_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Portfolio", cryptos_path, class:"nav-link" %>
        </li>
        
        <% if user_signed_in? %>

          <li class="nav-item">
           <%= link_to "Agregar", new_crypto_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Registrarse", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<center><h1>LISTADO CRIPTOMONEDAS</h1></center>


<div class="table-responsive"> 

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Símbolo</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      
      <th scope="col">%_cambio_1h</th>
      <th scope="col">%_cambio_24h</th>
      <th scope="col">%_cambio_7d</th>
     
      
     

    </tr>
  </thead>
  <tbody>
  	<% for x in @coins %>

    <tr>
      <th scope="row"><%= x["symbol"] %></th>
      <td><%= x["name"] %></td>
      <td><%= number_to_currency(x["quote"]["USD"]["price"]) %></td>
      
      <td><%= number_with_precision(x["quote"]["USD"]["percent_change_1h"], :precision=>2) %>%</td>
      <td><%= number_with_precision(x["quote"]["USD"]["percent_change_24h"], :precision=>2) %>%</td>
      <td><%= number_with_precision(x["quote"]["USD"]["percent_change_7d"], :precision=>2) %>%</td>
      
      
      
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/home/lookup.html.erb
<h1>Búsqueda de una Criptomoneda</h1>

 <form>
 	<div class="mb-3">
		 <%= form_tag home_lookup_path, :method => 'POST' do %>
		 <%= text_field_tag 'sym', nil, placeholder: "Entre símbolo de la criptomoneda", size: 50, class:"form-control" %>
		 <br/>
		 <%= submit_tag 'Buscar', class:"btn btn-primary" %>
		 <% end %>
	</div>
 </form>
 <br/><br/>




<% if @simbolo %>
	<% for x in @lookup_coin %>
		<% if @simbolo == x["symbol"] %>
			<strong>Nombre: </strong> <%= x["name"] %> <br/>
			<strong>Precio actual: </strong> <%= number_to_currency(x["quote"]["USD"]["price"]) %>
			
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "home/navbar" %>
    <br/>
    <div class="container">
      <%= render "home/flash" %>
      <%= yield %>
    </div>
  </body>
</html>